#!/usr/bin/sh

print_help () {
	echo "setup [Option|[BUILD_DIR] [COMPILE_FLAGS]]"
	echo ""
	echo "Options:"
	echo "--clean     remove all file not tracked by git"
	echo "--config    run ./configure after setting up build system"
	echo " --help     Show this help"
}
setup_build () {
	autoreconf --install
}
build_user_dir () {
	cur_dir=$(pwd)
	build_dir=$1
	shift
	autoreconf --install && \
		mkdir $build_dir && \
		pushd $build_dir && \
		$(realpath -s --relative-to=$(pwd) $cur_dir)/configure $@
}
main () {
	if [[ $# -eq 0 ]]; then
		setup_build
		exit 0
	fi
	case $1 in 
		"--help" | "-h")
			print_help
			;;
		"--config" | ".")
			./configure
			;;
		"--clean")
			git clean -fxd
			;;
		*)
			build_user_dir $@
	esac
}
main $@
